version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        APP_ENV: ${APP_ENV:-development}
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: ${APP_ENV:-development}

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
